DROP DATABASE IF EXISTS burger_db;
CREATE DATABASE burger_db;
USE burger_db;

CREATE TABLE burgers(
  id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
  burger_name VARCHAR(120),
  devoured BOOLEAN
);

